server:
  port: 8080
  rabbitmq:
    host: localhost
    port: 5672
spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: marvel
jse:
  rabbitmq:
    queue: jse.queue1
    exchange: jse.direct1
    routingkey: jse.routingkey1
jsf:
  rabbitmq:
    queue: jsf.queuereg
    exchange: jsf.directreg
    routingkey: jsf.routingkeyreg